const cycle=[["LP commits","LP 把资金承诺给 VC 基金，期待高风险资产带来超额回报。"],["GP invests","VC 合伙人筛选创业公司，下注少数可能产生巨大结果的机会。"],["Startup scales","创业公司用资金招聘、做产品、扩张市场，同时接受董事会治理。"],["Exit happens","上市、并购或失败清算让投资结果变成现金或损失。"],["Capital returns","回款分配给 LP 和 GP，影响下一只基金能否继续募资。"]];
const chapters=[
{no:"Introduction",title:"为什么创业者需要看懂 VC",summary:"作者说明本书目标：降低创业者和 VC 之间的信息不对称，让创业者在融资前知道自己将进入一段长期合作关系。",points:["VC 写支票只是开始，真正工作发生在融资后的公司建设中。","创业者要先判断自己的公司是否适合风险投资，而不是默认所有公司都该融资。","理解 VC 激励机制，才能判断对方行为背后的原因。"],note:"开场可以用“know your partner before you get married”解释融资关系的长期性。"},
{no:"Chapter 1",title:"Born in the Bubble",summary:"作者用自己在互联网泡沫时期的经历引入 VC 行业，展示高增长、泡沫、崩盘和创业韧性如何塑造一代投资人。",points:["1999-2000 年的泡沫让资本快速涌入科技公司，也暴露了估值和增长叙事的危险。","LoudCloud/Opsware 的经历让作者同时理解创业者和投资人的处境。","泡沫不是单纯的坏事，它也训练了市场理解技术公司生命周期。"],note:"这一章适合讲作者为什么有资格写这本实战指南。"},
{no:"Chapter 2",title:"So Really, What Is Venture Capital?",summary:"本章解释 VC 的本质：用高风险资金投资有极大上限的早期公司，通过少数赢家覆盖大量失败。",points:["VC 不是银行贷款，也不是普通股票投资，而是股权型、长期型、高失败率投资。","投资组合回报依赖少数公司大幅成功，所以市场规模和增长上限非常关键。","基金有期限、回报压力和 LP 责任，这会影响 VC 的投资选择。"],note:"这里要讲清楚为什么“小而美”公司未必适合 VC。"},
{no:"Chapter 3",title:"How Do Early-Stage VCs Decide Where to Invest?",summary:"本章拆解早期 VC 的决策逻辑：团队、市场、产品、时机、竞争和融资路径如何共同影响投资判断。",points:["早期投资数据很少，因此 VC 更依赖市场想象力、团队质量和故事可信度。","好项目通常要能回答：为什么现在、为什么你、为什么这个市场会很大。","VC 也会评估未来几轮融资是否可能继续获得资本支持。"],note:"展示时可以把它做成创业者 pitch 前的自查清单。"},
{no:"Chapter 4",title:"What Are LPs and Why Should You Care?",summary:"本章把镜头移到 VC 的上游：LP 是基金真正的资金来源，他们的目标会传导到 VC 决策中。",points:["LP 包括大学基金、养老金、基金中的基金、家族办公室等。","LP 选择 VC，是为了在资产配置中获得高风险、高回报、低流动性的创新资产敞口。","创业者理解 LP，可以理解为什么 VC 需要追求超大回报而不是普通利润。"],note:"讲 VC 时不要只看 GP，钱的源头也决定了游戏规则。"},
{no:"Chapter 5",title:"The Limited Edition: How LPs Team Up with VCs",summary:"本章解释 LP 与 VC 如何通过基金合同合作，包括管理费、carry、基金期限和利益绑定。",points:["VC 基金通常不是永久资本，而是有募集、投资、管理、退出的周期。","管理费支持机构运转，carry 激励 GP 追求投资收益。","基金结构会影响 VC 对退出时间、后续融资和风险承担的态度。"],note:"可以用“VC 也有老板”来帮助听众理解。"},
{no:"Chapter 6",title:"Forming Your Startup",summary:"本章从创业公司设立讲起，包括股权分配、员工期权、董事会结构和法律基础。",points:["创始人早期股权安排会长期影响团队激励和后续融资。","公司类型、期权池和董事会设置不是细枝末节，而是融资前的基础设施。","越早建立清晰规则，越能减少未来融资和团队冲突。"],note:"适合提醒创业者：融资问题很多在公司成立时就埋下了。"},
{no:"Chapter 7",title:"Raising Money from a VC",summary:"本章讨论如何启动融资：找对投资人、制造动量、控制节奏，并理解融资是销售过程。",points:["创业者需要研究 VC 的阶段、行业偏好和投资风格，不应盲目群发。","融资过程中的动量很重要，时间线和沟通节奏会影响谈判地位。","融资不是拿钱这么简单，而是在选择未来长期合作伙伴。"],note:"这一章可以作为创业者融资流程图来讲。"},
{no:"Chapter 8",title:"The Art of the Pitch",summary:"本章聚焦 pitch：如何用清晰故事呈现市场、产品、团队、增长和融资需求。",points:["好的 pitch 不是堆信息，而是让 VC 相信这个机会值得继续追问。","创业者要说明痛点、解决方案、市场规模、商业模式和团队优势。","诚实面对风险，比过度包装更能建立信任。"],note:"展示时可以给出一句话公式：问题很大、方案独特、团队能赢。"},
{no:"Chapter 9",title:"Term Sheets Part One: Economics",summary:"本章解释 Term Sheet 的经济条款，包括估值、投资金额、期权池、清算优先权和反稀释。",points:["估值不是唯一重点，清算优先权和期权池可能显著改变实际收益。","经济条款决定公司成功、普通成功或低价出售时各方如何分钱。","创业者要比较完整交易结构，而不是只看 headline valuation。"],note:"这是全书最适合做案例计算的一章。"},
{no:"Chapter 10",title:"Term Sheets Part Two: Governance",summary:"本章讲治理条款：董事会席位、保护性条款、投票权和创始人控制权。",points:["治理条款决定谁能对重大事项说 yes 或 no。","投资人保护自己资金的同时，也可能限制创始人的行动自由。","好的治理结构应该让各方在重大决策上透明协作，而不是制造僵局。"],note:"可以把 Chapter 9 和 10 对比为：一个讲钱，一个讲权。"},
{no:"Chapter 11",title:"The Deal Dilemma: Which Deal Is Better?",summary:"本章教创业者比较多个投资条款，判断哪个 deal 真正更好。",points:["更高估值不一定更好，条款、投资人质量、未来融资能力同样重要。","不同融资方案会影响创始人稀释、控制权和下轮融资难度。","创业者需要把眼前利益和长期公司建设放在一起权衡。"],note:"适合用两个虚拟 term sheet 对比讲。"},
{no:"Chapter 12",title:"Board Members and the Good Housekeeping Seal of Approval",summary:"本章讲董事会的功能：监督、建议、重大事项批准和对外信誉背书。",points:["董事会不是形式，它会影响融资、招聘、战略和创始人去留。","VC 董事既是投资人代表，也是公司建设资源。","健康董事会需要信息透明、角色清晰和共同目标。"],note:"讲这里可以强调：融资后 VC 坐上董事会，关系进入新阶段。"},
{no:"Chapter 13",title:"In Trados We Trust",summary:"本章通过 Trados 案例解释董事受托责任，以及在公司出售等关键情境下如何处理利益冲突。",points:["董事会成员对公司和股东负有法律责任，不只是代表某一方利益。","优先股、普通股、创始人和投资人的利益在低价退出时可能冲突。","理解受托责任能帮助创业者预判董事会决策边界。"],note:"这一章偏法律治理，适合用“董事到底为谁工作？”来开场。"},
{no:"Chapter 14",title:"Difficult Financings",summary:"本章讨论困难融资、down round、pay-to-play 等坏情境下的选择。",points:["公司发展低于预期时，融资条款会变得更苛刻，原有股东也可能被重新排序。","困难融资考验创始人、员工、投资人之间的信任。","提前理解条款，能在坏情境中减少被动。"],note:"可以提醒听众：Term Sheet 条款往往在坏时候才真正显现威力。"},
{no:"Chapter 15",title:"Exit Stage Left",summary:"本章讲好的退出：IPO、并购、上市准备、投行、锁定期和流动性。",points:["退出是 VC 生命周期的回款环节，也是创业公司进入新阶段的节点。","IPO 不只是敲钟，还涉及审计、治理、披露、市场窗口和长期投资人关系。","并购和上市各有利弊，关键是是否服务于公司长期价值。"],note:"这一章可以收束全书：钱从 LP 来，最后要通过退出回到 LP。"},
{no:"Conclusion",title:"The World Is Flat",summary:"结尾强调创业和风险投资机会不应只属于硅谷少数人，透明知识有助于扩大创业者群体。",points:["创业生态正在地理扩散，更多地区和人群可以参与创新。","让融资规则变透明，本身就是降低创业门槛的一部分。","书的最终目标是让创业者更有能力与资本平等对话。"],note:"最后可以回到“民主化创业机会”的主题。"}
];
function renderCycle(){const root=document.querySelector("#cycleList");root.innerHTML=cycle.map(([title,body],index)=>`<article class="cycle-item"><strong>${String(index+1).padStart(2,"0")} · ${title}</strong><p>${body}</p></article>`).join("");}
function renderChapters(){const query=document.querySelector("#search").value.trim().toLowerCase();const root=document.querySelector("#chapterGrid");const list=chapters.filter(chapter=>{const text=[chapter.no,chapter.title,chapter.summary,chapter.points.join(" "),chapter.note].join(" ").toLowerCase();return !query||text.includes(query);});root.innerHTML=list.map(chapter=>`<article class="chapter-card"><div class="chapter-meta"><span>${chapter.no}</span><span>VC Guide</span></div><h3>${chapter.title}</h3><p>${chapter.summary}</p><ul>${chapter.points.map(point=>`<li>${point}</li>`).join("")}</ul><div class="note">${chapter.note}</div></article>`).join("");if(!list.length)root.innerHTML=`<p class="empty">没有找到匹配内容，换个关键词试试。</p>`;}
renderCycle();renderChapters();document.querySelector("#search").addEventListener("input",renderChapters);
